[package]
name = "mensa-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
mensa-cli-backend = { git = "https://github.com/floork/mensa-cli-backend.git" }
tokio = "1.37.0"
